# Generated by Django 4.2.6 on 2023-10-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GISDSS',
            fields=[
                ('Assetid', models.IntegerField(primary_key=True, serialize=False)),
                ('StaffID', models.IntegerField()),
                ('AssetType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GISFeeders',
            fields=[
                ('Assetid', models.IntegerField(primary_key=True, serialize=False)),
                ('AssetName', models.CharField(max_length=255)),
                ('AssetType', models.CharField(max_length=255)),
                ('FeederName', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('NACCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PowerTransformers',
            fields=[
                ('Assetid', models.IntegerField(primary_key=True, serialize=False)),
                ('AssetType', models.CharField(max_length=255)),
                ('PT33KV11KVName', models.CharField(max_length=255)),
                ('PT33KV11KVParent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='outage.gisfeeders')),
            ],
        ),
        migrations.CreateModel(
            name='GISTransmissionSubstations',
            fields=[
                ('Assetid', models.IntegerField(primary_key=True, serialize=False)),
                ('AssetName', models.CharField(max_length=255)),
                ('AssetType', models.CharField(max_length=255)),
                ('CaptureDateTime', models.DateTimeField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('NACCode', models.CharField(max_length=255)),
                ('TS132KVName', models.CharField(max_length=255)),
                ('TS132KVRating', models.CharField(max_length=255)),
                ('TSAIN', models.CharField(max_length=255)),
                ('PT33KV11KVParent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='outage.powertransformers')),
            ],
        ),
        migrations.CreateModel(
            name='GISHighTension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetType', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('NACCode', models.CharField(max_length=255)),
                ('DSS11KV415VParent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='outage.gisdss')),
            ],
        ),
        migrations.AddField(
            model_name='gisfeeders',
            name='HT11KVParent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='outage.gishightension'),
        ),
    ]
