# Generated by Django 4.2.6 on 2023-10-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gistransmissionsubstations',
            old_name='PT33KV11KVParent',
            new_name='Powertrans',
        ),
    ]
