# Generated by Django 4.2.6 on 2023-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outage', '0003_gisfeeders_tech_engineer_gisfeeders_tech_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisfeeders',
            name='Tech_engineer_comment',
            field=models.CharField(default='no comment', max_length=255),
        ),
        migrations.AddField(
            model_name='gisfeeders',
            name='Tech_manager_comment',
            field=models.CharField(default='no comment', max_length=255),
        ),
        migrations.AddField(
            model_name='gisfeeders',
            name='Tech_supervisor_comment',
            field=models.CharField(default='no comment', max_length=255),
        ),
    ]
