# Generated by Django 4.2.6 on 2023-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outage', '0004_gisfeeders_tech_engineer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisfeeders',
            name='Tech_engineer_faultrectified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gisfeeders',
            name='Tech_manager_faultrectified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gisfeeders',
            name='Tech_supervisor_faultrectified',
            field=models.BooleanField(default=False),
        ),
    ]
